version: "3.4"

networks:
  default:

services:
  python-project:
    container_name: python-project
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        RUN_LEVEL: dev
        PYTHON_VERSION: "3.9"
      target: dev
    volumes:
      - .:/opt/app
    restart: unless-stopped
    env_file:
      - ./.env.local

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_name
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data