version: "3.4"

networks:
  default:

services:
  expo-food-bot:
    container_name: expo-food-bot
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        RUN_LEVEL: dev
        PYTHON_VERSION: "3.9"
      target: dev
    volumes:
      - .:/opt/app
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_name
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data

  redis:
    container_name: food-redis
    image: redis:7.0-rc-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./.docker_data/redis:/var/lib/redis