"""

Revision ID: 022951e9e9e3
Revises: 6248a1a3445f
Create Date: 2022-04-07 12:21:48.178681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022951e9e9e3'
down_revision = '6248a1a3445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodcategory',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('foodcategory_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('foodcategory_id')
    )
    op.create_index(op.f('ix_foodcategory_foodcategory_id'), 'foodcategory', ['foodcategory_id'], unique=False)
    op.add_column('food', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food', 'foodcategory', ['category_id'], ['foodcategory_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'category_id')
    op.drop_index(op.f('ix_foodcategory_foodcategory_id'), table_name='foodcategory')
    op.drop_table('foodcategory')
    # ### end Alembic commands ###
